baseURL = "https://www.ruudhendrikx.nl/"
languageCode = "en-us"
title = "Ruud Hendrikx"
enableRobotsTXT = true

[params]
  description = "AI Solution Engineer & Technical Leader"
  author = "Ruud Hendrikx"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
